name: Aria2本地下载
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      UrlFile:
        description: '下载URL文件路径'
        required: true
        default: 'urls.txt'
      Folder:
        description: '保存目录'
        required: true
        default: 'downloads'

jobs:
  Aria2-Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Aria2 Install
        run: sudo apt install -y aria2 rar python3
        
      - name: Downloading
        id: downloading
        run: |
          mkdir -p ${{ github.event.inputs.Folder }}
          while IFS= read -r line; do
            url=${line%##*}
            filename=${line##*##}
            
            # Replace spaces with underscores and remove non-ASCII characters
            sanitized_filename=$(echo "$filename" | sed 's/ /_/g' | sed 's/[^a-zA-Z0-9._-]/./g')
            
            echo "Downloading $sanitized_filename from $url"
            aria2c --seed-time=0 -d ${{ github.event.inputs.Folder }} -c "$url" -o "$sanitized_filename"
          done < ${{ github.event.inputs.UrlFile }}
          
      - name: Process Downloaded Files
        run: |
          python3 ./deal_download_files.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: env.path != '' && !cancelled() && !failure()
        with:
          name: downloaded-files
          path: result/*
        
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false



