name: Aria2本地下载
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: '下载URL'
        required: true
        default: 'https://网址##名称'
      Folder:
        description: '保存目录'
        required: true
        default: 'downloads'

jobs:
  Aria2-Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Aria2 Install
        run: sudo apt install -y aria2 rar python3
        
      - name: Downloading
        id: downloading
        run: |
          url="${{ github.event.inputs.Url}}"
          filename=${url##*##}
          downloadurl=${url%##*}
          mkdir -p ${{ github.event.inputs.Folder }}
          echo "path=${{ github.event.inputs.Folder }}/$filename" >> $GITHUB_ENV
          aria2c --seed-time=0 -d ${{ github.event.inputs.Folder }} -c "$downloadurl" -o "$filename"
          
      - name: Process Downloaded Files
        run: |
          python3 ./deal_download_files.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: env.path != '' && !cancelled() && !failure()
        with:
          name: downloaded-files
          path: result/*
        
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: "Release ${{ github.run_id }}"
          files: |
            result/*

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0


