name: Aria2 Batch Download

on:
  workflow_dispatch:

jobs:
  Aria2-Download:
    runs-on: ubuntu-latest
    steps:
      # 检出代码仓库
      - uses: actions/checkout@v2
      
      # 安装必要的依赖
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y aria2 python3

      # 从 url.list 下载文件
      - name: Download from url.list
        run: |
          mkdir -p downloads
          while IFS= read -r line || [ -n "$line" ]; do
            echo "Downloading $line"
            aria2c --seed-time=0 -d downloads -c "$line"
          done < url.list

      # 处理下载的文件
      - name: Process Downloaded Files
        run: |
          python3 ./deal_download_files.py

      # 上传下载的文件作为工件
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: downloads/*

      # 创建发布
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: "Release ${{ github.run_id }}"
          files: |
            downloads/*

      # 删除工作流运行记录
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
